runtime: nodejs22

service: <name>-gcp-sql-app

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 5

# Environment variables will be loaded via ENV directly
# through Google Cloud Console

handlers:
  - url: /.*
    script: auto

vpc_access_connector:
  name: projects/ml-training-sandbox-1/locations/asia-southeast1/connectors/cloud-run-vpc-connector
